### ISSUE TITLE
添加频道功能

### ISSUE THREAD

**Issue by CYZZ** [lexiaoyao20/FMTagsView#1]
这个库确实挺实用的，能否拓展到频道管理，类似网易新闻、今日头条、一点资讯，拥有长按排序功能，在点击更多频道会添加到我的频道中，希望完成之后拓展demo。

**Comment by lexiaoyao20** [comment]
多谢你的关注和肯定，这个周末我去实现一下~

**Comment by lexiaoyao20** [comment]
@CYZZ  
周末研究了一番，要去封装一套的话，其实还是要用到UICollectionView，然后还是要公开DataSource和Delegate出来，感觉就没必要去进一步封装了。
频道管理功能其实也就是用两个UICollectionView去实现的，创建UIColectionViewCell的子类来定制外观，然后拖动排序可以参考这两个库：[LewReorderableLayout](https://github.com/pljhonglu/LewReorderableLayout)  和 [LXReorderableCollectionViewFlowLayout](https://github.com/lxcid/LXReorderableCollectionViewFlowLayout) ; Cell里面显示编辑模式样式，其实也就是显示一个删除按钮（普通状态下是隐藏的），删除时候数据项里的项也要跟着删除，然后调用UICollectionView里的方法deleteItemsAtIndexPaths: 或者reloadData方法。

**Comment by CYZZ** [comment]
好的，非常感谢，我去研究一下看看如何实现相关的功能，如果你有比较好的demo易于拓展的话请通知我谢谢。
