### ISSUE TITLE
多选状态下，代理是否点击不响应

### ISSUE THREAD

**Issue by lceboy** [lexiaoyao20/FMTagsView#11]
多选状态下，代理是否点击不响应

**Comment by lexiaoyao20** [comment]
你的意思是说多选模式下，`- (void)tagsView:(FMTagsView *)tagsView didSelectTagAtIndex:(NSUInteger)index`  这个代理方法没有被调用吗？

**Comment by lexiaoyao20** [comment]
已修复此问题~
