### ISSUE TITLE
- (BOOL)tagsView:(FMTagsView *)tagsView shouldDeselectItemAtIndex:(NSUInteger)index;不执行

### ISSUE THREAD

**Issue by pengchifei** [lexiaoyao20/FMTagsView#2]
- (BOOL)collectionView:(UICollectionView *)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath *)indexPath {
  if ([self.delegate respondsToSelector:@selector(tagsView:didDeSelectTagAtIndex:)]) {
      return [self.delegate tagsView:self shouldDeselectItemAtIndex:indexPath.row];
  }
  return YES;
  }
- (BOOL)collectionView:(UICollectionView *)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath *)indexPath {
  if ([self.delegate respondsToSelector:@selector(tagsView:shouldDeselectItemAtIndex:)]) {
      return [self.delegate tagsView:self shouldDeselectItemAtIndex:indexPath.row];
  }
  return YES;
  }

**Comment by lexiaoyao20** [comment]
看了官方文档，说是多选模式下才会调用

```
// called when the user taps on an already-selected item in multi-select mode
- (BOOL)collectionView:(UICollectionView *)collectionView shouldDeselectItemAtIndexPath:(NSIndexPath *)indexPath; 
```

你设为多选模式试下： `tagsView.allowsMultipleSelection = YES;`
