### ISSUE TITLE
The frame height doesn't adjust after layoutIfNeeded

### ISSUE THREAD

**Issue by albert0m** [lexiaoyao20/FMTagsView#3]
Still learning objective c, but apparently once you set the frame with

FMTagsView *tagsView = [[FMTagsView alloc] initWithFrame:CGRectMake(10, 10, 320, 190)];

the frame doesn't autoadjust to the right height when you set

[tagsView layoutIfNeeded];

or

UICollectionView *collectionView = tagsView.subviews.firstObject;
[collectionView layoutIfNeeded];

Why is that?

**Comment by lexiaoyao20** [comment]
Can you show me your full code？
I have updated the demo code，in file of CustomerViewController.m，but did not encounter the problem you said.

My english is poor, I do't know if you can understand what I said.

**Comment by albert0m** [comment]
your english is fine, don't worry!

My problem is that I need to resize the frame after I draw the tags because I don't know the number of tags and probably is more or less than the initial given size (in your example the height is 190). I programmatically put the tagView in a scrollView and after drawing the tagView, the height is too much and it doesn't resize.

This is what happens:
<img width="317" alt="schermata 2017-07-27 alle 11 58 17" src="https://user-images.githubusercontent.com/779070/28665130-ea5e6c22-72c2-11e7-87c3-856be0eb966f.png">

how can I make the view resize after I draw it and fit the real used height?

Thank you

**Comment by lexiaoyao20** [comment]
It's my control's bug. You must set the tagsView with the correct width. 

```
- (FMTagsView *)createTagsViewWithDataSrouse:(NSArray *)dataSource borderColor:(UIColor *)borderColor {
    CGFloat screenWidth = [UIScreen mainScreen].bounds.size.width;
    CGFloat padding = 15;
    //must set the correct width
    FMTagsView *tagsView = [[FMTagsView alloc] initWithFrame:CGRectMake(0, 0, screenWidth - padding * 2, 180)];
    tagsView.backgroundColor = [UIColor whiteColor];
    tagsView.delegate = self;
    tagsView.contentInsets = UIEdgeInsetsMake(10, 10, 10, 10);
    tagsView.tagcornerRadius = 0;
    tagsView.layer.borderColor = borderColor.CGColor;
    tagsView.layer.borderWidth = 1;
    tagsView.tagsArray = dataSource;
    
    return tagsView;
}
```
![2017-07-27 7 24 59](https://user-images.githubusercontent.com/3021017/28668258-91908794-7301-11e7-83e2-21402cc16b7a.png)

The code has been updated， wish to help you.

**Comment by albert0m** [comment]
so basically the magic happens because of the Costraints part. I commented a piece of your code and this is what I had already reported at the beginning:

<img width="908" alt="schermata 2017-08-21 alle 17 00 05" src="https://user-images.githubusercontent.com/779070/29525275-5e74a90e-8692-11e7-8fd1-4f6a21a053a8.png">

The tagview height is exactly 180 like configured at the beginning.
Is there any way to set the constraints dynamically?? I'm working with dynamic zones and I don't have label1, label2, label3.. Sorry but I'm very new to objective c and constraints are still really hard to understand.

What if I didn't use constraints? how can I resize the view without those?

**Comment by lexiaoyao20** [comment]
Becasue the scrollview's contentSize is determined by its internal subviews, in my code, the scrollContentView's size is determined by its subviews, and the scrollView's contentSize is determined by the `scrollCotentView`.

```
[self.scrollContentView mas_makeConstraints:^(MASConstraintMaker *make){
        make.bottom.equalTo(self.tagsView3.mas_bottom).offset(10);
    }];
```

I have add a new method called `changeDataSource` in my latest code, this change the tagsview's height dynamically, As shown below:

![autolayout](https://user-images.githubusercontent.com/3021017/29555471-5230b43a-8755-11e7-96f4-538ca4ff0b6d.gif)


I recommend you some information to learn Autolayout:
1. [ Using UIScrollView with Auto Layout in iOS ](https://spin.atomicobject.com/2014/03/05/uiscrollview-autolayout-ios/)
2. [AutolayoutExampleWithMasonry](https://github.com/zekunyan/AutolayoutExampleWithMasonry)
3. [Beginning Auto Layout Tutorial in iOS 7: Part 1](https://www.raywenderlich.com/50317/beginning-auto-layout-tutorial-in-ios-7-part-1)
4. [Beginning Auto Layout Tutorial in iOS 7: Part 2 ](https://www.raywenderlich.com/50319/beginning-auto-layout-tutorial-in-ios-7-part-2)

**Comment by albert0m** [comment]
thank you so much for your help! since I dynamically created the views, I ended up doing something as simple as this:

`for (int x =0;x<arrayView.count;x++) {

                                if (x-1>=0) {

                                    UIView *previousView = arrayView[(NSUInteger) (x-1)];
                                    UIView *currentView = arrayView[(NSUInteger) (x)];
                                    [currentView mas_makeConstraints:^(MASConstraintMaker *make){
                                        make.top.equalTo(previousView.mas_bottom).offset(15);
                                        make.left.equalTo(previousView);
                                    }];
                                }

                            }`

not sure if there is any better way to achieve this, but this is good as a beginning!
